spring.application.name=usedcar

#Database
#spring.datasource.url=jdbc:postgresql://localhost:5433/usedcar
#spring.datasource.username=postgres
#spring.datasource.password=D4v3f1ucsk402!
spring.jpa.open-in-view=false
logging.level.org.hibernate.SQL=debug
logging.level.org.hibernate.type.descriptor.sql=trace
logging.level.org.hibernate.engine.transaction=trace
spring.jpa.hibernate.ddl-auto=update
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

#Auth0
#spring.security.oauth2.resourceserver.jwt.issuer-uri=https://dev-qxpiaj7nftetek0r.us.auth0.com/
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=20MB


# Vault
spring.cloud.vault.config.lifecycle.enabled=false
spring.cloud.vault.namespace=admin
logging.level.org.springframework.cloud.vault=DEBUG
logging.level.org.springframework.vault=DEBUG
logging.level.org.springframework.boot.context.config=DEBUG
spring.config.import=vault://
spring.cloud.vault.uri=${VAULT_ADDR}
spring.cloud.vault.authentication=TOKEN
spring.cloud.vault.token=${VAULT_TOKEN}

spring.cloud.vault.kv.enabled=true
spring.cloud.vault.kv.backend=secret
spring.cloud.vault.kv.application-name=used-car