spring.application.name=usedcar

#Database
spring.jpa.open-in-view=false
logging.level.org.hibernate.SQL=debug
logging.level.org.hibernate.type.descriptor.sql=trace
logging.level.org.hibernate.engine.transaction=trace
spring.jpa.hibernate.ddl-auto=update
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

#Auth0
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=20MB

#Vault
spring.cloud.vault.config.lifecycle.enabled=false
spring.config.import=vault://

spring.cloud.vault.uri=${VAULT_URL}
spring.cloud.vault.authentication=TOKEN
spring.cloud.vault.token=${VAULT_TOKEN}
spring.cloud.vault.namespace=admin

spring.cloud.vault.kv.enabled=true
spring.cloud.vault.kv.backend=secret

spring.cloud.vault.kv.application-name=used-car
spring.cloud.vault.kv.default-context=used-car

logging.level.org.springframework.cloud.vault=TRACE
logging.level.org.springframework.vault=TRACE
logging.level.org.springframework.boot.context.config=DEBUG
